context:
  version: "0.10.1"
  build_number: 0

package:
  name: "xeus-lua"
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-lua/archive/${{ version }}.tar.gz
  sha256: fd9f9d9e40b7c2ff864a0b0d2cf50cbd8038edcb660590c934fbe7c5c041244e

build:
  number: ${{ build_number }}

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: unix
      then:
        - make
  host:
    - if: linux
      then:
        - openlibm
    - lua >=5.2.0,<5.5
    - xeus-zmq >=4.0.0,<5
    - nlohmann_json
    - xwidgets >=0.30,<0.31
    - xcanvas >=0.7,<0.8

tests:
  - package_contents:
      files:
        exists:
          - ${{ "Library/" if win }}bin/xlua${{ ".exe" if win }}
          - ${{ "Library/" if win }}share/jupyter/kernels/xlua/kernel.json
          - ${{ "Library/" if win }}include/xeus-lua/xinterpreter.hpp
          - ${{ "Library/" if win }}lib/cmake/xeus-lua/xeus-luaConfig.cmake
          - ${{ "Library/" if win }}lib/cmake/xeus-lua/xeus-luaConfigVersion.cmake

about:
  homepage: https://github.com/jupyter-xeus/xeus-lua
  repository: https://github.com/jupyter-xeus/xeus-lua
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Lua kernel for Jupyter based on xeus
  description: Jupyter kernel for the Lua programming language
  documentation: https://xeus-lua.readthedocs.io

extra:
  recipe-maintainers:
    - JohanMabille
    - DerThorsten
    - SylvainCorlay
